version: "2.3"
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
      - ./keycloak-db:/opt/jboss/keycloak/standalone/data
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=pass
      - DB_VENDOR=h2
    ports:
      - 8080:8080